#
# AUTO-GENERATED BY FabActUtil - DO NOT MODIFY
#

# BEGIN ApplicationManifest

$AppPackageName = "VoicemailBoxActorAppPkg"
$AppName = "fabric:/VoicemailBoxActorApp"
$AppTypeName = "VoicemailBoxActorAppType"
$AppTypeVersion = "2.0.0.0"
$ActorServiceUriMap = @{}
$ActorServiceIsStatefulMap = @{}
$ActorServiceHasPersistedStateMap = @{}

# END ApplicationManifest

# BEGIN ServiceManifest VoicemailBoxActorServicePkg

$ActorServiceUriMap["IVoicemailBoxActor"] = "fabric:/VoicemailBoxActorApp/VoicemailBoxActorService";
$ActorServiceUriMap["Microsoft.ServiceFabric.Actors.Samples.IVoicemailBoxActor"] = "fabric:/VoicemailBoxActorApp/VoicemailBoxActorService";

$ActorServiceIsStatefulMap["IVoicemailBoxActor"] = $True;
$ActorServiceIsStatefulMap["Microsoft.ServiceFabric.Actors.Samples.IVoicemailBoxActor"] = $True;

$ActorServiceHasPersistedStateMap["IVoicemailBoxActor"] = $True;
$ActorServiceHasPersistedStateMap["Microsoft.ServiceFabric.Actors.Samples.IVoicemailBoxActor"] = $True;


# END ServiceManifest VoicemailBoxActorServicePkg
