#
# AUTO-GENERATED BY FabActUtil - DO NOT MODIFY
#

# BEGIN ApplicationManifest

$AppPackageName = "HelloWorldActorAppPkg"
$AppName = "fabric:/HelloWorldActorApp"
$AppTypeName = "HelloWorldActorAppType"
$AppTypeVersion = "1.0.0.0"
$ActorServiceUriMap = @{}
$ActorServiceIsStatefulMap = @{}
$ActorServiceHasPersistedStateMap = @{}

# END ApplicationManifest

# BEGIN ServiceManifest HelloWorldActorServicePkg

$ActorServiceUriMap["IHello"] = "fabric:/HelloWorldActorApp/HelloActorService";
$ActorServiceUriMap["Microsoft.ServiceFabric.Actors.Samples.IHello"] = "fabric:/HelloWorldActorApp/HelloActorService";

$ActorServiceIsStatefulMap["IHello"] = $False;
$ActorServiceIsStatefulMap["Microsoft.ServiceFabric.Actors.Samples.IHello"] = $False;



# END ServiceManifest HelloWorldActorServicePkg
